sudo: false
language: python
install:
  - pip install tox==1.9.2 coveralls
env:
  - TOX_ENV=py27
  - TOX_ENV=py3
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
script:
  - tox -e $TOX_ENV -v
after_success:
  coveralls

 