sudo: required
language: python
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-9.4 postgresql-contrib-9.4 postgresql-plpython-9.4
  - sudo -u postgres createdb test
  - sudo -u postgres createlang plpython2u test
install:
  - pip install jinja2
script:
  - >
      sudo -u postgres psql -d test -c 'CREATE FUNCTION py_test()
                                   RETURNS void LANGUAGE plpythonu AS $$
                                     import jinja2
                                   $$;'
  - sudo -u postgres psql -d test -c 'SELECT py_test();'
