language: python
addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-plpython-9.4
install:
  - pip install jinja2
script:
  - psql -U postgres -c 'CREATE DATABASE test;'
  - psql -U postgres -c 'CREATE EXTENSION plpythonu;'
  - psql -U postgres -d test -c 'CREATE LANGUAGE plpythonu;'
  - >
      psql -U postgres -d test -c 'CREATE FUNCTION py_test()
                                   RETURNS void LANGUAGE plpythonu AS $$
                                     import jinja2
                                   $$;'
  - psql -U postgres -d test -c 'SELECT py_test();'

